[package]
name = "clockwork-base32"
version = "0.1.0"
authors = ["woxtu <woxtup@gmail.com>"]
edition = "2018"
description = "Clockwork Base32 encoding/decoding"
license = "MIT"

[dependencies]
bit-vec = "0.6"
